name: hello
'on':
  workflow_dispatch:
    inputs:
      thename:
        description: What is your name?
        required: true
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: 'echo "Hello ${{ inputs.thename }}"'
